//! Market ABI, calldata layout and error codes.

use starknet::ContractAddress;

/// Input for depositing to an open note, returned by an invoked contract.
///
/// Must match `privacy::objects::OpenNoteDeposit` field for field: the pool deserializes the
/// return value of `privacy_invoke` into this shape (positional Serde), then pulls `amount` of
/// `token` from this contract and writes it into the open note `note_id`.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct OpenNoteDeposit {
    pub note_id: felt252,
    pub token: ContractAddress,
    pub amount: u128,
}

/// The ERC20 surface the market needs. Declared here only to build a dispatcher.
#[starknet::interface]
pub trait IErc20<TState> {
    fn balance_of(self: @TState, account: ContractAddress) -> u256;
    fn transfer(ref self: TState, recipient: ContractAddress, amount: u256) -> bool;
    fn approve(ref self: TState, spender: ContractAddress, amount: u256) -> bool;
}

/// Where a claim's payout goes. The claim signature covers this choice, so the target cannot be
/// swapped by whoever relays the transaction.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub enum PayoutTarget {
    /// Pay into an open note created in the same pool transaction, keeping the payout inside the
    /// pool as a private note-to-note transfer. The note id is assigned by the wallet during
    /// assembly (calldata placeholder `${openNoteIds[0]}`), so it cannot be signed ahead of time:
    /// an `OpenNote` claim is a bearer authorization for the transaction that carries it.
    OpenNote: felt252,
    /// Pay by ERC20 transfer to `recipient`. The recipient is known when the coupon is signed, so
    /// this authorization is bound: a copied signature can only ever pay the same address.
    Address: ContractAddress,
}

/// Stake `amount` on `outcome` of `market_id`, owned by `position_key`.
///
/// The pool withdraws the stake into this contract before the invoke runs, so `amount` is checked
/// against the contract's own token balance rather than trusted.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct BetInput {
    pub market_id: u64,
    pub outcome: u8,
    pub amount: u128,
    /// Stark public key that owns the resulting position. Generated by the bettor, never their
    /// wallet key: it is the only handle on the position and it appears in the `BetPlaced` event.
    pub position_key: felt252,
}

/// Collect the payout of the position `(market_id, outcome, position_key)`.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct ClaimInput {
    pub market_id: u64,
    pub outcome: u8,
    pub position_key: felt252,
    /// Stark signature by `position_key` over
    /// [`claim_message_hash`](crate::market::claim_message_hash).
    pub signature_r: felt252,
    pub signature_s: felt252,
    pub target: PayoutTarget,
}

/// The action the pool asks the market to perform.
///
/// Serialized positionally into the `invoke` action's calldata, variant index first:
/// - `Bet`: `[0, market_id, outcome, amount, position_key]`
/// - `Claim` into an open note: `[1, market_id, outcome, position_key, r, s, 0, note_id]`
/// - `Claim` to an address: `[1, market_id, outcome, position_key, r, s, 1, recipient]`
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub enum MarketAction {
    Bet: BetInput,
    Claim: ClaimInput,
}

/// Lifecycle of a market.
#[derive(Copy, Drop, Serde, PartialEq, Debug, starknet::Store)]
pub enum MarketState {
    /// Accepting bets until `close_at`. The zero value, so a market is open the moment it exists.
    #[default]
    Open,
    /// Settled on `winning_outcome`; positions on it can claim a share of the pot.
    Resolved,
    /// Cancelled; every position reclaims exactly its own stake.
    Void,
}

/// A market's public state. Question and outcome labels are stored separately because a
/// `ByteArray` cannot live in a `Copy` struct.
#[derive(Copy, Drop, Serde, PartialEq, Debug, starknet::Store)]
pub struct Market {
    /// The only address allowed to resolve or void this market. An oracle adapter contract can
    /// hold this role, which is how price questions resolve without the market hardcoding a feed.
    pub resolver: ContractAddress,
    /// Bets are rejected from this timestamp on, and resolution is refused before it.
    pub close_at: u64,
    pub n_outcomes: u8,
    pub state: MarketState,
    /// Meaningful only in state `Resolved`.
    pub winning_outcome: u8,
    /// Total staked across every outcome. The whole pot goes to the winning outcome's positions.
    pub pot: u128,
}

#[starknet::interface]
pub trait IVeilcastMarket<TState> {
    /// Opens a market on `question` with one label per outcome. Returns its id.
    fn create_market(
        ref self: TState,
        question: ByteArray,
        outcome_labels: Array<ByteArray>,
        resolver: ContractAddress,
        close_at: u64,
    ) -> u64;

    /// Settles `market_id` on `winning_outcome`. Resolver only, and only once the market has
    /// closed. A winning outcome nobody backed voids the market instead of stranding the pot.
    fn resolve(ref self: TState, market_id: u64, winning_outcome: u8);

    /// Cancels `market_id` so every position can reclaim its stake. The resolver may void an
    /// unsettled market at any time; anyone may void one left open `VOID_GRACE` past its close,
    /// so a silent resolver cannot lock the pot forever.
    fn void(ref self: TState, market_id: u64);

    /// Places a bet or collects a payout on behalf of a pool user. Callable only by the pool,
    /// through the `privacy_invoke` selector.
    fn privacy_invoke(ref self: TState, action: MarketAction) -> Span<OpenNoteDeposit>;

    fn get_market(self: @TState, market_id: u64) -> Market;
    fn get_question(self: @TState, market_id: u64) -> ByteArray;
    fn get_outcome_label(self: @TState, market_id: u64, outcome: u8) -> ByteArray;
    /// Staked amount per outcome, in outcome order. This is the public price signal.
    fn get_outcome_volumes(self: @TState, market_id: u64) -> Span<u128>;
    /// Remaining stake of one position, zero once claimed.
    fn get_stake(self: @TState, market_id: u64, outcome: u8, position_key: felt252) -> u128;
    /// What `stake` would collect if `outcome` won: the settled share for a resolved market, the
    /// live quote including the new stake for an open one.
    fn quote_payout(self: @TState, market_id: u64, outcome: u8, stake: u128) -> u128;
    fn get_n_markets(self: @TState) -> u64;
    fn get_pool(self: @TState) -> ContractAddress;
    fn get_token(self: @TState) -> ContractAddress;
    /// Tokens this contract owes to open positions and unclaimed payouts.
    fn get_total_escrow(self: @TState) -> u128;
}

pub mod errors {
    pub const UNAUTHORIZED_CALLER: felt252 = 'UNAUTHORIZED_CALLER';
    pub const NOT_RESOLVER: felt252 = 'NOT_RESOLVER';
    pub const ZERO_POOL: felt252 = 'ZERO_POOL';
    pub const ZERO_TOKEN: felt252 = 'ZERO_TOKEN';
    pub const ZERO_RESOLVER: felt252 = 'ZERO_RESOLVER';
    pub const ZERO_AMOUNT: felt252 = 'ZERO_AMOUNT';
    pub const ZERO_POSITION_KEY: felt252 = 'ZERO_POSITION_KEY';
    pub const ZERO_RECIPIENT: felt252 = 'ZERO_RECIPIENT';
    pub const NO_MARKET: felt252 = 'NO_MARKET';
    pub const TOO_FEW_OUTCOMES: felt252 = 'TOO_FEW_OUTCOMES';
    pub const TOO_MANY_OUTCOMES: felt252 = 'TOO_MANY_OUTCOMES';
    pub const CLOSE_IN_PAST: felt252 = 'CLOSE_IN_PAST';
    pub const NO_SUCH_OUTCOME: felt252 = 'NO_SUCH_OUTCOME';
    pub const MARKET_CLOSED: felt252 = 'MARKET_CLOSED';
    pub const MARKET_NOT_CLOSED: felt252 = 'MARKET_NOT_CLOSED';
    pub const MARKET_SETTLED: felt252 = 'MARKET_SETTLED';
    pub const MARKET_UNSETTLED: felt252 = 'MARKET_UNSETTLED';
    pub const VOID_TOO_EARLY: felt252 = 'VOID_TOO_EARLY';
    pub const STAKE_NOT_FUNDED: felt252 = 'STAKE_NOT_FUNDED';
    pub const NO_POSITION: felt252 = 'NO_POSITION';
    pub const LOSING_POSITION: felt252 = 'LOSING_POSITION';
    pub const BAD_CLAIM_SIGNATURE: felt252 = 'BAD_CLAIM_SIGNATURE';
    pub const POT_OVERFLOW: felt252 = 'POT_OVERFLOW';
    pub const PAYOUT_OVERFLOW: felt252 = 'PAYOUT_OVERFLOW';
}
